"""
Mapping configuration: FactGrid properties to GND MARC 21 fields.

Based on 'Anforderungen GND_FG_neu.xlsx', sheet 'Personen_GND'.
"""

# FactGrid ISIL
ISIL = "DE-4218"

# Leader for person authority records
LEADER = "00000nz  a2200000nc 4500"

# Constant control fields
CONSTANT_CONTROLFIELDS = {
    "003": ISIL,
}

# Constant data fields (always included)
CONSTANT_DATAFIELDS = [
    {
        "tag": "040",
        "ind1": " ",
        "ind2": " ",
        "subfields": [
            {"code": "a", "value": ISIL},
            {"code": "9", "value": "r:DE-101"},
            {"code": "b", "value": "ger"},
            {"code": "e", "value": "rda"},
        ],
    },
    {
        "tag": "042",
        "ind1": " ",
        "ind2": " ",
        "subfields": [
            {"code": "a", "value": "gnd4"},
        ],
    },
    {
        "tag": "075",
        "ind1": " ",
        "ind2": " ",
        "subfields": [
            {"code": "b", "value": "p"},
            {"code": "2", "value": "gndgen"},
        ],
    },
    {
        "tag": "075",
        "ind1": " ",
        "ind2": " ",
        "subfields": [
            {"code": "b", "value": "piz"},
            {"code": "2", "value": "gndspec"},
        ],
    },
    {
        "tag": "079",
        "ind1": " ",
        "ind2": " ",
        "subfields": [
            {"code": "a", "value": "g"},
            {"code": "q", "value": "d"},
        ],
    },
]

# FactGrid property to MARC field mappings
# Each entry describes which MARC fields to generate from a FactGrid property.

# Property IDs
PROP_GND_ID = "P76"
PROP_BIRTH_DATE = "P77"
PROP_DEATH_DATE = "P38"
PROP_INSTANCE_OF = "P2"
PROP_OCCUPATION = "P165"  # Beruf/Taetigkeit
PROP_FAMILY_NAME = "P247"
PROP_GIVEN_NAME = "P248"
PROP_BIRTH_PLACE = "P82"  # Geburtsort
PROP_DEATH_PLACE = "P168"  # Sterbeort
PROP_PLACE_OF_ACTIVITY = "P83"  # Ort der Adresse (Wirkungsort)
PROP_PLACE_OF_ACTIVITY_2 = "P1372"  # Wirkungsort (alternative property)

# Wirkungsdaten (activity dates) — only used as a 548 $4=datw fallback when no
# life dates (P77/P38) are present.
PROP_ACTIVITY_START = "P1504"  # Wirkungsbeginn
PROP_ACTIVITY_END = "P1505"  # Wirkungsende
# Datierte Einzelereignisse, die als Wirkungsdatum dienen können (erweiterbar).
ACTIVITY_EVENT_PROPS = ["P392"]  # P392 = Datum der Disputation
# GND element set URL for 548 $4=datw
GND_PERIOD_OF_ACTIVITY = "https://d-nb.info/standards/elementset/gnd#periodOfActivity"

# Validation: mandatory MARC tags for a valid GND person record.
# Per DNB guideline EH-P-16 (Anhang "Pflichtfelder", specs/
# Individualisierungsrichtlinie_GND.pdf), field 548 is fakultativ — it is an
# individualization criterion, not a mandatory field — so it is NOT listed here.
MANDATORY_TAGS = ["001", "003", "005", "008", "035", "040", "043", "075", "079", "100"]

# Individualization criteria for GND Level 1
# Need at least 3 total, at least 1 from Group 1.
# Keys are criterion identifiers built as "<tag>-<$4-code>", NOT bare MARC tags,
# because the group assignment per the DNB guideline EH-P-16
# ("Individualisierungsrichtlinie") depends on the $4 sub-type, not just the tag:
#   - 548 splits into datl (approximate life dates), datx (exact life dates) and
#     datw/datz (activity dates),
#   - 550 splits into berc (characteristic profession) vs. beru and others,
#   - 551 splits into ortg/orts/ortw/ortx (birth/death/activity/exile place),
# and each of these is a distinct identifying feature. See EH-P-16, "Individua-
# lisierungsmerkmale der Gruppe 1 / Gruppe 2".
INDIVIDUALIZATION_GROUP1 = {
    "548-datl": "Nicht-exakte Lebensdaten (datl)",
    "550-berc": "Beruf oder Taetigkeit (berc)",
    # 500 $4=pseu/nawi (Pseudonym<->wirklicher Name) is a Group-1 feature in
    # EH-P-16 but is not generated by this converter.
}

INDIVIDUALIZATION_GROUP2 = {
    "548-datx": "Exakte Lebensdaten (datx)",
    "548-datw": "Wirkungsdaten (datw)",
    "548-datz": "Wirkungsdaten exakt (datz)",
    "551-ortg": "Geburtsort",
    "551-orts": "Sterbeort",
    "551-ortw": "Wirkungsort",
    "551-ortx": "Exilort",
    "550-beru": "Weitere Berufe/Taetigkeiten (beru)",
    "550-adel": "Adelstitel",
    "550-them": "Taetigkeitsbereich/Fachgebiet/Thema",
    "550-istr": "Instrument",
    "550-stud": "Studienfach",
    # Further Group-2 features in EH-P-16 not generated here: 500 (beza/bezb/
    # bezf/korr), 510/511/551 affi, 672, 678, 377, 024.
}

# Allowed $4 sub-type codes per tag, used to derive individualization criteria.
INDIVIDUALIZATION_SUBTYPE_CODES = {
    "548": ("datl", "datx", "datw", "datz"),
    "550": ("berc", "beru", "adel", "them", "istr", "stud"),
    "551": ("ortg", "orts", "ortw", "ortx"),
}

MIN_INDIVIDUALIZATION_TOTAL = 3
MIN_INDIVIDUALIZATION_GROUP1 = 1

# MARC field descriptions (German) for UI display
FIELD_DESCRIPTIONS = {
    "001": "Kontrollnummer",
    "003": "ISIL der einspielenden Einrichtung",
    "005": "Zeitstempel der letzten Transaktion",
    "008": "Datenelemente mit fester Laenge",
    "035": "Maschinelle Erzeugung GND Nummer",
    "040": "Katalogisierungsquelle",
    "042": "Authentifizierungscode",
    "043": "Laendercode",
    "075": "Entitaetentyp",
    "079": "Teilbestandskennzeichnung",
    "100": "Bevorzugter Personenname",
    "400": "Abweichender Name",
    "548": "Lebensdaten",
    "550": "Beruf/Taetigkeit",
    "551": "Orte",
    "667": "Redaktionelle Bemerkung",
    "670": "Quellenangabe",
}
